### ISSUE TITLE
Commented on PR over and over again

### ISSUE THREAD

**Issue by Pranc1ngPegasus** [k1LoW/octocov-action#1]
Thank you for provide nice actions.
I have the problem that i got commented on PR over and over again if i run this actions again.
Can you update PR comment if I run this actions again?

Thanks

**Comment by k1LoW** [comment]
Comments will not be updated. Always make a new comment.

If you want to delete previous comments, please enable [`comment.deletePrevious:`](https://github.com/k1LoW/octocov#commentdeleteprevious).

**Comment by Pranc1ngPegasus** [comment]
Thanks for explaining. This was exactly what I needed!
